### ISSUE TITLE
Object Features + Multi training

### ISSUE THREAD

**Issue by MuMuJun97** [MuMuJun97/vl_nav#16]
```shell
git checkout multi
torchrun --nnodes=1 --nproc_per_node=8 --master_port 49008 duet/llm_vl/training_merge.py --run_name _opt_object_demo1 --cfg_file tools/cfgs/exp/multi.yaml --batch_size 8 --num_epochs 20 --tokenizer_path facebook/opt-iml-1.3b --lr 5e-5 --precision fp32
```
- Image Features: `/mnt/petrelfs/zhaolin/vln/nav/vl_nav/build/duet/R2R/features/view_timm_imagenet_vitb16` 
- Object Features:  `/mnt/petrelfs/zhaolin/vln/nav/vl_nav/build/duet/SOON/features/obj2d_ade20k_timm_vitb16` 
https://github.com/MuMuJun97/vl_nav/blob/6917ab4cac7be5fb57d53bf8ee8cb585f339af97/duet/llm_vl/training_merge.py#L45-L46

- 配置文件说明: `tools/cfgs/exp/multi.yaml` 
```yaml
  SOURCE: ['SOON', 'R2R', 'REVERIE', 'CVDN'] # 四个下游任务训练
  SOON: # SOON更新为使用ADE30K Object Label的GT Files
    DIR: "data/SOON/annotations/ade30k" # train.json
    SPLIT: {
      "train": "train_enc_pseudo_obj_ade30k_label.jsonl",
      "val_seen": "val_unseen_instrs_enc_pseudo_obj_ade30k_label.jsonl",
      "val_unseen": "val_unseen_house_enc_pseudo_obj_ade30k_label.jsonl",
      "test": "None"
    }
```
